version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: airline_postgres
    restart: always
    environment:
      POSTGRES_USER: airline_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: egypt_airways
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: